name: deploymnet-workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo Hello, ${{ inputs.username }}

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
       - name: check user permission
         uses: 74th/workflow-permission-action@1.0.0
         with:
           users: vikramk2
          
       - name: Deploy
         run: echo Hello, ${{ inputs.username }}
  
