name: deploymnet-workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo Hello, ${{ inputs.username }}
      - name: Test
        env:
          TESTC: ${{ secrets.TESTC }}
        run: |
          echo Password is env.TESTC
          echo Diret ${{ secrets.TESTC }}
          echo Diret11 ${{ env.TESTC }}
          if [[ env.TESTC == *"PROD"* ]]; then
            echo "This is the PROD password!"
          else
            echo "This is NOT the PROD password!"
          fi
        
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    
    steps:
       - name: check user permission
         uses: 74th/workflow-permission-action@1.0.0
         with:
           users: vikramk20
       - uses: trstringer/manual-approval@v1
         with:
           secret: ${{ github.token }}
           approvers: vikramk20   
       - name: Deploy
         run: echo Hello, ${{ inputs.username }}
  
